
CREATE TABLE DEVICE (
	DEV_ID BIGINT NOT NULL AUTO_INCREMENT,
	DEV_UID VARCHAR(25) NOT NULL,
	DEV_REG_ID VARCHAR(4000),
	DEV_NAME VARCHAR(255),
	DEV_ACT BOOL,
	DEV_OWNER BIGINT NOT NULL,
	PRIMARY KEY (DEV_ID),
	FOREIGN KEY (DEV_OWNER) REFERENCES USER(USER_ID)
);

CREATE TABLE REQUEST (
	REQ_ID BIGINT NOT NULL AUTO_INCREMENT,
	REQ_NAME VARCHAR(255),
	REQ_FILE_LOC VARCHAR(255),
	REQ_FILE_BASE_DIR VARCHAR(16), 
	REQ_FILE_ID BIGINT,
	REQ_STAT VARCHAR(16),
	REQ_STAT_MSG VARCHAR(255) DEFAULT '',
	REQ_UPD TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	REQ_DEV_ID BIGINT,
	REQ_OWNER BIGINT NOT NULL,
	PRIMARY KEY (REQ_ID),
	FOREIGN KEY (REQ_DEV_ID) REFERENCES DEVICE(DEV_ID),
	FOREIGN KEY (REQ_FILE_ID) REFERENCES FILE(FILE_ID),
	FOREIGN KEY (REQ_STAT) REFERENCES REQUEST_STATUS(REQ_STAT_VAL),
	FOREIGN KEY (REQ_FILE_BASE_DIR) REFERENCES REQUEST_BASE_DIR(REQ_BASE_DIR),
	FOREIGN KEY (REQ_OWNER) REFERENCES USER(USER_ID)
)

CREATE TABLE REQUEST_STATUS (
	REQ_STAT_VAL VARCHAR(16) NOT NULL,
	PRIMARY KEY (REQ_STAT_VAL)
);

CREATE TABLE REQUEST_BASE_DIR (
	REQ_BASE_DIR VARCHAR(16) NOT NULL,
	PRIMARY KEY (REQ_BASE_DIR)
);

CREATE TABLE FILE (
	FILE_ID BIGINT NOT NULL AUTO_INCREMENT,
	FILE_VAL MEDIUMBLOB,
	FILE_NAME VARCHAR(255),
	PRIMARY KEY (FILE_ID)
);

INSERT INTO REQUEST_STATUS (REQ_STAT_VAL)
VALUES ('NEW'),
	  ('IN_PROGRESS'),
	  ('FAILED'),
	  ('COMPLETED');


INSERT INTO REQUEST_BASE_DIR (REQ_BASE_DIR)
VALUES ('ROOT'),
	  ('DOCUMENTS'),
	  ('DOWNLOADS'),
	  ('MOVIES'),
	  ('MUSIC'),
	  ('PICTURES');
	  
	  
	  
CREATE TABLE USER (
	USER_ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_USERNAME VARCHAR(50) NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	USER_ACTIVE BIT NOT NULL,
	USER_LOCKED BIT NOT NULL,
	USER_EXP_DATE TIMESTAMP NULL DEFAULT NULL,
	USER_PASSWORD_EXP_DATE TIMESTAMP NULL DEFAULT NULL,	
	PRIMARY KEY (USER_ID)

)

CREATE TABLE AUTHORITY (
	AUTHORITY VARCHAR(50) NOT NULL,
	PRIMARY KEY (AUTHORITY)
)

CREATE TABLE USER_AUTHORITY (
	USER_AUTH_ID BIGINT NOT NULL AUTO_INCREMENT,
	USER_ID BIGINT NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
	FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITY(AUTHORITY),
	PRIMARY KEY (USER_AUTH_ID)
)

INSERT INTO AUTHORITY (AUTHORITY) 
VALUES ('ROLE_ADMIN'),
	   ('ROLE_USER')
	   

/** Test Data */

INSERT INTO USER (USER_USERNAME, USER_PASSWORD, USER_ACTIVE, USER_LOCKED)
VALUES		  ('mitchell','password1', 1, 0),
			  ('admin','password1', 1, 0);



INSERT INTO user_authority (USER_ID, AUTHORITY)
VALUES                     (1, 'ROLE_USER'),
                           (2, 'ROLE_USER'),
                           (2, 'ROLE_ADMIN')
						   